### ISSUE TITLE
[Bug] Auto reload on save

### ISSUE THREAD

**Issue by stripuramallu3** [creativetimofficial/ct-soft-ui-dashboard-pro-react#18]
### Version
3.0.0
### Reproduction link
https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro-react/
### Operating System
macOS Monterey
### Device
Macbook Pro 15-inch
### Browser & Version
Chrome 98.0.4758.109
### Steps to reproduce
When a change is made to a file and saved, the app is reloaded (as expected). However, the resulting UI on the browser is frozen. For example, button clicks, scrolling, etc are not possible.
### What is expected?
Page is not frozen, so button clicks, scrolling, etc are possible. 
### What is actually happening?
Page is frozen after app reload.

---
### Solution
Refresh the page in the browser (Control + R)

**Comment by stripuramallu3** [comment]
This issue occurs with the provided build that is downloaded.

1. Start the dev server `npm start`
2. Make a small change (add character to text, change variable name, etc)
3. Navigate back to brower page of app and it is frozen (not possible to make button clicks, open menus, etc)

**Comment by sajadevo** [comment]
> This issue occurs with the provided build that is downloaded.
> 
> 1. Start the dev server `npm start`
> 2. Make a small change (add character to text, change variable name, etc)
> 3. Navigate back to brower page of app and it is frozen (not possible to make button clicks, open menus, etc)

**Hi @stripuramallu3 **

Thanks for using our product please update it to version v3.1.0 we've just released it and this issue is fix on the new version of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
