### ISSUE TITLE
Project imports

### ISSUE THREAD

**Issue by SrGiiL** [creativetimofficial/ct-soft-ui-dashboard-pro-react#22]
Hello

I have one proble with imports, all project files import aren't clickable due the imports are generated of wrong form, the imports must start with src path. In this way after performing the ctrl + click action, it takes you to the corresponding file.

Thanks for your help

**Comment by sajadevo** [comment]
**Hi @SrGiiL**

Thanks for using our product and letting us to make it better for solving these sort of bugs, I will put your issue open and on the next update I will take care of that issue.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by SrGiiL** [comment]
Hello @sajadevo 

I'm solving the problem using ViteJS, I'm transforming the project right from the start, file to file.

I already have the solution but refactoring all the files takes a lot of time.

Best.

**Comment by sajadevo** [comment]
**Hi @SrGiiL**

Thanks awesome, please lemme know if you need my help on your side, I will fix this issue for the CRA as well, since most of the people are still using CRA for their project.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
